# Stage 1: Build Angular App
FROM node:22 AS builder

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies using npm ci (requires package-lock.json)
RUN npm ci

# Run tests
RUN npm test -- --watch=false --browsers=ChromeHeadless

# Copy the rest of the project files
COPY . .

# Build Angular app
RUN npm run build -- --configuration=production
